language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t akshat4916/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akshat4916/docker-react npm run test -- -- coverage
